### ISSUE TITLE
Starship Shields Do Not Calculate correctly.

### ISSUE THREAD

**Issue by insomniabob** [wildj79/foundryvtt-starfinder#130]
under module/rules/actions/starship/calculate-max-shields.js, there is a formula:

const shieldMax = Math.max(Math.floor(data.attributes.shields.max * 0.7), 1);

The 0.7 value should be .25 to correctly calculate the maximum value o the shields divided by 4.

**Comment by wildj79** [comment]
The calculation is correct, but might not be needed. There isn't actually any mention of a "maximum" amount of shields that you can assign to any one quadrant. This was a logical conclusion based on math. The "minimum" value that you can assigned to a quadrant is 10% of the total shield value provided to the ship when combat begins and when you balance the shields. If you have 4 quadrants, then the maximum amount that you could assign to any one quadrant would be 70% of the total, the other 30% going to the other quadrants because they each have to have at least 10%.
