### ISSUE TITLE
NPC Starships aren't adding Gunnery mod

### ISSUE THREAD

**Issue by jessekruger** [wildj79/foundryvtt-starfinder#264]
There doesn't seem to be anywhere to allocate Gunnery skill points for NPC starships, so weapons don't utilize Gunnery added from stat blocks.

**Comment by TimToxopeus** [comment]
In order to keep the Starship Actions working consistently across both PC and NPC starships, you are required to use the Piloting skill for that on the gunner NPC position. Just set the Gunnery bonus as Piloting ranks. Probably, it's good to write a little UI element for that somewhere, as it is not immediately apparent.
