### ISSUE TITLE
Unable to Add Description to new Drone Item

### ISSUE THREAD

**Issue by fatigues65** [wildj79/foundryvtt-starfinder#380]
When creating an entirely new Drone Item entry, it is not possible to add a description long short or a GM note to the Item. The edit symbol does appear in the text field.  Details may be edited, but the description cannot be.

**Comment by TimToxopeus** [comment]
I cannot reproduce this. My steps to reproduce were:
1. Open drone sheet
2. Go to features tab
3. Add a new mod
4. Click mod edit button
5. On the mod's details tab, switch to short description tab
6. Click text edit button and enter a text
7. Hit save
8. Close drone mod item sheet
9. Re-open drone mod item sheet and check short description tab
10. See text I entered.

Are any of my steps different from yours?

**Comment by fatigues65** [comment]
I have retraced; it appears that the new drone item I had specified was a
"chassis" not an item. There are two options in the drop down when you
create the Drone item, apparently I had kept selecting "chassis". That
can't be described - probably because there is already a number of
items present on that drone, including s chassis.

The new item description, when specified to be an "item" and not a chassis,*
is* describable.

I have wasted your time. I apologize.

.Robert

**Comment by LebombJames** [comment]
I would like to resurrect this issue, I find many item types are uneditable. However, it looks only like ones without a "sidebar" (the one that says "passive") are uneditable e.g themes, classes, archetypes. Feats are editable because they have a sidebar.

This explains the bug @fatigues65 experienced. The Drone chassis item doesn't have a sidebar.

It's also worth noting normally uneditable item types that have entries in the compendium _are_ editable, sidebar or not.

**Comment by TimToxopeus** [comment]
Gotcha. It's not that they're uneditable, it's just that because the sidebar is missing the text box height is set to 0 making it very difficult to edit, which I suppose comes down to the same thing. :D Either way, I think I have already fixed this issue, I now ensure a height.
