### ISSUE TITLE
Bad item type for Null-space Chamber, Mk 1, 2, 3 (compendium)

### ISSUE THREAD

**Issue by SebH68** [wildj79/foundryvtt-starfinder#394]
Hello
for the items : 

- Null-space Chamber, Mk 1
- Null-space Chamber, Mk 2
- Null-space Chamber, Mk 3
the item type should be _'hybrid'_ and not _'container'_

**Comment by wildj79** [comment]
While you're not wrong per se, this one is gonna stay the way it is. We use the `container` type here for mechanical reasons, so that the item behaves the way it's expected to behave. The `container` type is used internally by the system to determine if said item is indeed used as a container. So, while technically this item is a `hybrid` item (in terms of game nomenclature), it needs to be a `container` so that the game system handles it correctly.
