### ISSUE TITLE
Changing an skill misc. modifiers to a formula can break a character sheet

### ISSUE THREAD

**Issue by ViniciosCoelho** [wildj79/foundryvtt-starfinder#437]
### How to reproduce it:
1. Go to an skill in a created character and right click it.
2. Change the **Misc. Modifiers** to something like "1d6".
3. Submit it.
4. Close the sheet.
5. Try to open it again.

### Result
The sheet cannot be open anymore.

### Expected result
The added modifier should give an error if not correct or accept the formula correctly.
Either way, the sheet shouldn't break to the point where it can't be open.

### Additional notes
The json property related with **Misc. Modifiers** gets set to "**null**" instead the default value, which is "**0**".

**Comment by wildj79** [comment]
Hmm... yeah, that would be an issue.

This is an older system that was put in place in the very early stages of development. At the time, there wasn't really a way to process dice rolls in these types of fields. The foundry API has grown quite a bit since then, but this never got updated in newer versions. To be honest, I think the way to go moving forward would be to completely remove the field. It's kind of out lived its usefulness, since the modifier system does the same thing, only better.

**Comment by TimToxopeus** [comment]
! You found it! I've been trying to figure out why the misc modifiers was getting set to null for nearly a year now, but no-one ever provided steps to reproduce it. I never thought to try put a non-numeric value in there! Awesome find!

**Comment by TimToxopeus** [comment]
Entering a formula into the skill's misc. modifiers field would break your character sheet because it gets parsed to null as it is not a number. The field is supposed to be numeric only, but since no validator is run on it anything was accepted. Switched input type to number only.
