### ISSUE TITLE
Feature Request: add gunnery skill to npc crew on starships

### ISSUE THREAD

**Issue by Dosendusche** [wildj79/foundryvtt-starfinder#458]
Since i couldn't even find an acceptable workaround it would be nice to have this. It's strange nobody seems to have an issue with that.
Nearly all Paizo Statblocks for Starships have this skill.

**Comment by CptTwinkie** [comment]
The workaround is piloting ranks. I personally don't like this as a workaround since it's a little confusing and it means you have a somewhat random number for piloting ranks. So I would also like to see gunnery listed as a skill. I would be perfectly happy to see it listed everywhere.

Although it could really be house-ruled to be used anywhere you are operating very heavy weaponry or perhaps call it remote weaponry such as aiming satellite lasers or mechanized planetary defense guns or something crazy like that.

**Comment by Dosendusche** [comment]
i'm a little late sorry! 
Was added here: https://github.com/wildj79/foundryvtt-starfinder/releases/tag/v0.19.0
PR is mentioned above.
closing now, big thanks to @LebombJames.
