### ISSUE TITLE
[Feature Request] Add a better system to track modifiers.

### ISSUE THREAD

**Issue by Iankid** [wildj79/foundryvtt-starfinder#48]
I'm a big fan of the Starfinder by Roll20 sheet on roll20. so I was hoping for a few features to be replicated on there.

In particular, I want to be able, As a Player, add in abilities I can just checkbox to apply to my character. E.G. Damai have an ability that gives them bonuses to skills if underground. in Roll20, I just click a checkbox I made beforehand to add the numbers into the skill rolls.

Another request is more homebrew friendly features. This is a very general request, but an example I have after messing with the sheet. I was seeing if I can modify the CMD for a -4 bonus to the total, but wasn't able to. Or the ability to give extra skill points to players (I'm involved with a game with those homebrew rules)

Lastly, and this is somewhat actually would be important to the SF ruleset. A way to catagorize bonus types, so you cannot stack bonus types that shouldn't be able to.

Thank you for your hard work on this sheet so far. I hope it continues to improve.

**Comment by wildj79** [comment]
This will all be covered in my modifiers updates. I'm going to be adding in a modifiers system that will allow players to add a modifier to just about anything. You will be able to specify a type and everything should stack correctly. I also plan for these to have a checkbox that you can use to toggle them on or off. They won't be included in the v0.2.5 update that is coming out in the next day or two, but that release has a lot of the underlying code needed to make them work. I plan to roll this feature out over several releases, because it is a big jump for the system.

Also, be aware that you could already modify skills. You can right click on them to add in additional miscellaneous modifiers.

**Comment by HubbeKing** [comment]
For reference, this is how the PF2e foundry module handles custom modifiers:
https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/blob/master/src/module/actor/actor.js#L81-85
https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/blob/master/src/module/actor/actor.js#L805-844

Essentially just storing an array of custom PF2Modifiers, which they already use in the module to modify things - https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/blob/master/src/module/modifiers.js#L64

Similar functions in this module would be handy, to allow for adding modifiers to players or items by name - the Solarian's Solar Armor ability comes to mind - having an easy way to toggle the bonus to AC would be nice.

**Comment by wildj79** [comment]
Thanks, I'll take a look.

**Comment by wildj79** [comment]
Partially implemented in #65 .
