### ISSUE TITLE
Bonus Modifier on skill checks when in dice format not working

### ISSUE THREAD

**Issue by xanstin** [wildj79/foundryvtt-starfinder#493]
Trying to add a 1d6 bonus insight modifier to a skill doesn't roll the dice for use in Skill Expertise. The same modifier works fine if I change the dropdown to weapon damage as far as format goes.

![image](https://user-images.githubusercontent.com/26841771/147853787-efaf9859-f753-423e-85e4-35c76199f207.png)

Have this error in the console when rolling the skill

![image](https://user-images.githubusercontent.com/26841771/147853814-36ea5c51-303d-4f1b-abfd-d1991471730a.png)

**Comment by TimToxopeus** [comment]
The main issue is that you are applying it as a constant modifier. You shouldn't put dice rolls into constant modifiers as dice rolls are not a constant value. Switch constant modifier to situational modifier, or make the modifier a constant value instead.

The error is unrelated, there's a known issue with the chat card display, but it doesn't negatively affect functioning of anything, as it just fails to display nothing, and then displays nothing because that part failed. :)

**Comment by xanstin** [comment]
Oh ok so make it an always enabled situational modifier. Constant with d6 worked with weapon damage didn't think to try situational .

Thank you
