### ISSUE TITLE
Allow modifiers to affect to-hit and damage rolls

### ISSUE THREAD

**Issue by HubbeKing** [wildj79/foundryvtt-starfinder#70]
Allowing custom modifiers to add bonuses to attack and damage rolls would allow for more flexible homebrew stuff, and allow for easily toggle-able abilities (for instance, the Solarian's Plasma Sheath)

**Comment by wildj79** [comment]
It's on the schedule for the next release.

**Comment by darkpelos** [comment]
This would be very helpful to emulate the Weapon Focus and Weapon Specialization traits while those aren't native on the system.

**Comment by wildj79** [comment]
@darkpelos those things can already be emulated without the need for modifiers. For weapon focus, add a +1 (or +2, if your BAB is low enough) to the damage field. For weapon specialization, you can use @attributes to do this in the damage formula. For example, for a Azimuth Laser Rifle, in the damage field you can do `1d8 + @details.level.value` and for a Azimuth Laser Pistol (or any other small arm) `1d4 + floor(@details.level.value / 2)`

**Comment by darkpelos** [comment]
@wildj79 Oh thanks, that worked! (there is an way to round down the valor?)

And other question, in the weapons section there is an "Attack Roll Bonus" field that I think isn't working. Think I could add the attack bonus from there, or set the attack of NPCs with that field... is that something that i'm missing?

**Comment by wildj79** [comment]
`floor(numberOrEquation)` -> rounds down
`ceil(numberOrEquation)` -> rounds up
`round(numberOrEquation)` -> follows standard rounding rules (< 0.5 rounds down, >= 0.5 rounds up)
`max(firstNum, secondNum[, thirdNum...])` -> returns the higher of the sequence of numbers
`min(firstNum, secondNum[, thirdNumb...])` -> returns the smaller of the sequence of numbers

Basically, any method that is available on the javascript `Math` object is available for use in the damage formula field.

As for your other question, it's a known issue that will be fixed in the upcoming release.

**Comment by TimToxopeus** [comment]
Modifier support for attack rolls and weapon damages has been added to 0.3.6.

**Comment by wildj79** [comment]
Added in latest release.
